//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIFSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CircuitoCampeonato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CircuitoCampeonato()
        {
            this.RegistroDisputa = new HashSet<RegistroDisputa>();
        }
    
        public int Id { get; set; }
        public long TempoMaximoParaConclusao { get; set; }
        public Nullable<int> TentativasTreino { get; set; }
        public Nullable<int> TentativasDisputa { get; set; }
        public Nullable<int> NumeroVoltasTreino { get; set; }
        public Nullable<int> NumeroVoltasDisputa { get; set; }
        public string Discriminator { get; set; }
        public Nullable<int> Campeonato_Id { get; set; }
        public Nullable<int> Circuito_Id { get; set; }
    
        public virtual Campeonato Campeonato { get; set; }
        public virtual Circuito Circuito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroDisputa> RegistroDisputa { get; set; }
    }
}
