//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIFSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circuito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Circuito()
        {
            this.CircuitoCampeonato = new HashSet<CircuitoCampeonato>();
            this.Campeonato = new HashSet<Campeonato>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Sigla { get; set; }
        public int Tamanho { get; set; }
        public int Complexidade { get; set; }
        public byte[] Imagem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CircuitoCampeonato> CircuitoCampeonato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campeonato> Campeonato { get; set; }
    }
}
