//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIFSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipeCampeonato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipeCampeonato()
        {
            this.RegistroDisputa = new HashSet<RegistroDisputa>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Campeonato_Id { get; set; }
        public Nullable<int> Equipe_Id { get; set; }
    
        public virtual Campeonato Campeonato { get; set; }
        public virtual Equipe Equipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroDisputa> RegistroDisputa { get; set; }
    }
}
