//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIFSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembroCampeonato
    {
        public int Id { get; set; }
        public Nullable<int> Campeonato_Id { get; set; }
        public Nullable<int> Usuario_Id { get; set; }
    
        public virtual Campeonato Campeonato { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
