//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIFSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroDisputa
    {
        public int Id { get; set; }
        public System.DateTime DataRegistro { get; set; }
        public bool EhTreino { get; set; }
        public int Sequencial { get; set; }
        public System.TimeSpan Tempo { get; set; }
        public int CircuitoCampeonato_Id { get; set; }
        public Nullable<int> EquipeCampeonato_Id { get; set; }
        public Nullable<int> Usuario_Id { get; set; }
    
        public virtual CircuitoCampeonato CircuitoCampeonato { get; set; }
        public virtual EquipeCampeonato EquipeCampeonato { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
